// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SentimentRazorML.Model
{
    public class ModelInput
    {
        [ColumnName("cleanText"), LoadColumn(0)]
        public string CleanText { get; set; }


        [ColumnName("compoundScoresVader"), LoadColumn(1)]
        public string CompoundScoresVader { get; set; }


        [ColumnName("discreteSentiment"), LoadColumn(2)]
        public string DiscreteSentiment { get; set; }


    }
}
